# Generated by Django 3.2.14 on 2023-01-28 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('District', models.CharField(blank=True, max_length=255, null=True)),
                ('SearchKeyword', models.CharField(blank=True, max_length=255, null=True)),
                ('Image', models.ImageField(blank=True, max_length=500, null=True, upload_to='images')),
                ('Title', models.CharField(blank=True, max_length=255, null=True)),
                ('PicUrl', models.CharField(blank=True, max_length=255, null=True)),
                ('DetailUrl', models.CharField(blank=True, max_length=255, null=True)),
                ('Price', models.CharField(blank=True, max_length=255, null=True)),
                ('PromotionPrice', models.CharField(blank=True, max_length=255, null=True)),
                ('Sales', models.CharField(blank=True, max_length=255, null=True)),
                ('NumIid', models.CharField(blank=True, max_length=255, null=True)),
                ('SellerNick', models.CharField(blank=True, max_length=255, null=True)),
                ('SellerID', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('District', models.CharField(blank=True, max_length=255, null=True)),
                ('SearchKeyword', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
