# Generated by Django 3.2.14 on 2023-01-28 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='Image',
        ),
    ]
