# Generated by Django 4.1.5 on 2023-01-28 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_items_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='Image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='images'),
        ),
    ]
