# Generated by Django 3.2.14 on 2023-01-28 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_items_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='Image',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='images'),
        ),
    ]
