# Generated by Django 3.2.14 on 2023-01-29 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_items_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='Image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
