# Generated by Django 3.2.14 on 2023-01-30 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_items_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('District', models.CharField(blank=True, max_length=255, null=True)),
                ('NumIid', models.CharField(blank=True, max_length=255, null=True)),
                ('JsonPath', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
